name: Deploy Slidev Multi-Branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'minggu-*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build with Dynamic Base Path
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          BRANCH_NAME=${{ github.ref_name }}
          
          npx slidev build --base /${REPO_NAME}/${BRANCH_NAME}/

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.ref_name }}
          clean: false
